[package]
name = "picoc"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
bril = { git = "https://github.com/sampsyo/bril", package = "bril-rs" }
[dev-dependencies]
insta = "1.43.1"